### ISSUE TITLE
this module is not support tengine 2.1.2？ 

### ISSUE THREAD

**Issue by Michael754267513** [cubicdaiya/ngx_dynamic_upstream#13]
this module is only support nginx 1.9.0 ？ i saw readme，this is support nginx-1.9.0-plus？

**Comment by cubicdaiya** [comment]
> this module is only support nginx 1.9.0 ？ i saw readme，this is support nginx-1.9.0-plus？

It is available in 1.9.x or later.

> this module is not support tengine 2.1.2？

Yes.

**Comment by Michael754267513** [comment]
i test nginx 1.9.12，this module is ok，are you thinking about it with support tengine？

**Comment by cubicdaiya** [comment]
> are you thinking about it with support tengine？

I have no plan now. Because `ngx_dynamic_upstream` requires the directive `zone` in upstream context for sharing upstreams with each nginx worker process. But tengine does not have it.

**Comment by Michael754267513** [comment]
3Q
