### ISSUE TITLE
Question about module?

### ISSUE THREAD

**Issue by xluffy** [cubicdaiya/ngx_dynamic_upstream#22]
Have I a question? `ngx_dynamic_upstream` modify on memory, so it's very fast. What has happened when backend instance handling a lot of connections. When backend instance execute the request and complete it, how to response to the user?

**Comment by sunyq** [comment]
UP

**Comment by xluffy** [comment]
@sunyq hi, I think I discover the answer. I think it works same `nginx -s reload`, an old worker process will handle old requests. And when an old request is complete at backend server, it's response to old worker process, an old worker process is a response to the user and old worker is shutdown. 

But i can't verify it, ref http://nginx.org/en/docs/beginners_guide.html#control
