### ISSUE TITLE
About installation guide.

### ISSUE THREAD

**Issue by William-Hunter** [cubicdaiya/ngx_dynamic_upstream#27]
Hi guy,I am try to compile this modules recently,  but I can't MAKE nginx after I put this modules join to config . I get some error just following:

`
make[1]: *** No rule to make target /opt/nginx_code/ngx_dynamic_upstream/src/src/ngx_dynamic_upstream_module.h', needed by objs/addon/src/ngx_dynamic_upstream_module.o'.  Stop.
`
Can you tell me how to sovle this problem?

And I suggest you put some installation guide in readme file.
Have a good day.

**Comment by zhubijia** [comment]
I also need  installation guide .

**Comment by zhubijia** [comment]
> Hi guy,I am try to compile this modules recently, but I can't MAKE nginx after I put this modules join to config . I get some error just following:
> 
> `make[1]: *** No rule to make target /opt/nginx_code/ngx_dynamic_upstream/src/src/ngx_dynamic_upstream_module.h', needed by objs/addon/src/ngx_dynamic_upstream_module.o'. Stop.`
> Can you tell me how to sovle this problem?
> 
> And I suggest you put some installation guide in readme file.
> Have a good day.

Have you installed successful?

**Comment by zhubijia** [comment]
> > Hi guy,I am try to compile this modules recently, but I can't MAKE nginx after I put this modules join to config . I get some error just following:
> > `make[1]: *** No rule to make target /opt/nginx_code/ngx_dynamic_upstream/src/src/ngx_dynamic_upstream_module.h', needed by objs/addon/src/ngx_dynamic_upstream_module.o'. Stop.`
> > Can you tell me how to sovle this problem?
> > And I suggest you put some installation guide in readme file.
> > Have a good day.
> 
> Have you installed successful?
just like:
--add-module=./ngx_dynamic_upstream-master

**Comment by William-Hunter** [comment]
@zhubijia
Finally,I make it work.
thanks for your tips.

**Comment by ygm521** [comment]
@William-Hunter not nginx plus , it can work!

**Comment by William-Hunter** [comment]
that's my mistake,this issue should be close.
