### ISSUE TITLE
Is   list all the upstream zone  needed?

### ISSUE THREAD

**Issue by diluke1600** [cubicdaiya/ngx_dynamic_upstream#9]
I have so many upstreams,can it provide list all the upstream  status ?

**Comment by cubicdaiya** [comment]
@huamaolin 

> can it provide list all the upstream status ?

At present, no. Now `ngx_dynamic_upstream` provides the APIs for manipulating one upstream once.

It may be provided a directive such as `dynamic_upstream_list` in the feature.

**Comment by igorastds** [comment]
there's no good way to get ngx_dynamic_upstream_create_response_buf workng with configs of other upstreams as I see..

**Comment by diluke1600** [comment]
thanks
